/**
 * Phase 5a — stdlib Option / Result.
 *
 * Verifies the stdlib Silicon source files type-check and compile through
 * the full pipeline.  Tests use textual concatenation rather than @use so
 * they exercise the type-system path without depending on filesystem
 * resolution (which is itself covered by useResolver.test.ts).
 */

import { test, expect, describe } from 'bun:test'
import { readFileSync } from 'fs'
import { join } from 'path'
import parse from '../parser'
import addToAstSemantics from '../ast/toAst'
import siliconGrammar from '../grammar/SiliconGrammar'
import elaborate from '../elaborator/elaborator'
import { buildStrataRegistry } from '../elaborator/strataLoader'
import { compileStrataHandlers } from '../comptime/engine'
import typecheck from '../types/typechecker'
import { lowerProgram } from '../ir/lower'
import { emitModule } from '../ir/emit'

const optionSrc = readFileSync(join(__dirname, 'option.si'), 'utf-8')
const resultSrc = readFileSync(join(__dirname, 'result.si'), 'utf-8')

function parseProgram(src: string): any {
    return addToAstSemantics(siliconGrammar)(parse(src)).toAst() as any
}

async function compile(src: string) {
    const prog = parseProgram(src)
    const registry = buildStrataRegistry(prog)
    await compileStrataHandlers(prog, registry)
    const elab = elaborate(prog, registry)
    const { program: typedProg, functions, errors } = typecheck(elab.program, registry)
    const mod = lowerProgram(typedProg, registry, functions)
    return { mod, registry, errors }
}

describe('Phase 5a-1: Option stdlib', () => {
    test('option.si parses and typechecks standalone', async () => {
        const { errors } = await compile(optionSrc)
        expect(errors.length).toBe(0)
    })

    test('Option[Int] usage via &Some / &None type-checks', async () => {
        const { errors } = await compile(`${optionSrc}
            @fn pick:Int := &option_unwrap_or (&Some 42), 0;
            @fn miss:Int := &option_unwrap_or (&None), 7;
        `)
        expect(errors.length).toBe(0)
    })

    test('Option[Int] and Option[Float] remain distinct nominal types', async () => {
        // Negative test: passing a Float Some to a function expecting Option[Int]
        // should produce a type error.
        const { errors } = await compile(`${optionSrc}
            @fn want_int x:Option[Int] := &option_unwrap_or x, 0;
            @fn wrong:Int := &want_int (&Some 1.5);
        `)
        expect(errors.length).toBeGreaterThan(0)
    })

    test('option_unwrap_or compiles end-to-end and emits a callable function', async () => {
        const { mod } = await compile(`${optionSrc}
            @fn pick:Int := &option_unwrap_or (&Some 42), 0;
        `)
        const wat = emitModule(mod, '')
        // The synthesised match-arms reduce to ifs, so the WAT contains
        // both branches' value paths.
        expect(wat).toContain('(func $pick')
        // Constructors should resolve as named calls; pick must call unwrap_or.
        expect(wat).toContain('option_unwrap_or')
    })
})

describe('Phase 5a-2: Result stdlib', () => {
    test('result.si parses and typechecks standalone', async () => {
        const { errors } = await compile(resultSrc)
        expect(errors.length).toBe(0)
    })

    test('@type Result[T, E] declaration registers as a sum type with two variants', async () => {
        const { mod } = await compile(resultSrc)
        // The variant constructors Some/None for Option, Ok/Err for Result
        // are generated by the parametric sum-type lowering.  We see them
        // as globals / functions in the module.
        const wat = emitModule(mod, '')
        expect(wat).toContain('Ok')
        expect(wat).toContain('Err')
    })

    test('Pattern-match on Result via @match returns the right branch type', async () => {
        // No explicit annotation — inference flows from &Ok 42 / &Err arg.
        const { errors } = await compile(`${resultSrc}
            @fn pick:Int := {
                &@match (&Ok 42),
                    $Ok v => v,
                    $Err _e => 0
            };
        `)
        expect(errors.length).toBe(0)
    })

    test('&Ok and &Err constructors infer T and E from arg shape', async () => {
        // Without an explicit type annotation on the binding the inferred
        // type is `Result[Int, ?E]` for &Ok 42 — the constructor is
        // polymorphic in E since &Ok doesn't carry the error type.
        // This proves the variant constructors lower correctly even when
        // the annotation-position multi-arg limitation prevents pinning.
        const { errors } = await compile(`${resultSrc}
            @fn pick:Int := {
                @local r := &Ok 42;
                &@match r,
                    $Ok v   => v,
                    $Err _e => 0
            };
        `)
        expect(errors.length).toBe(0)
    })
})

describe('Phase 5a: stdlib types coexist in one program', () => {
    test('Option and Result both load together without name collisions', async () => {
        const { errors } = await compile(`${optionSrc}\n${resultSrc}
            @fn use_both:Int := {
                @local maybe:Option[Int] := &Some 7;
                @local r := &Ok 42;
                @local picked := &@match r, $Ok v => v, $Err _e => 0;
                (&option_unwrap_or maybe, 0) + picked
            };
        `)
        expect(errors.length).toBe(0)
    })
})
