// SPDX-License-Identifier: MIT
/**
 * Generate src/assets.generated.ts — the inlined, filesystem-free copy of
 * every compiler asset the pipeline reads at runtime (grammar, strata,
 * built-in modules, std.wat, stdlib, web platform).
 *
 * This exists so the compiler can run in a browser, where there is no
 * filesystem. The Bun/Node toolchain still reads these files from disk via
 * the `*Source.ts` modules; only the browser bundle uses this generated copy
 * (through the `*Source.browser.ts` variants). Regenerate after editing any
 * .si / .ohm / .wat asset that the browser playground must ship:
 *
 *   bun run compiler/scripts/gen-web-assets.ts
 */

import { readdirSync, readFileSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const SRC = join(dirname(fileURLToPath(import.meta.url)), '..', 'src')

const read = (rel: string) => readFileSync(join(SRC, rel), 'utf-8')
const lit = (s: string) => JSON.stringify(s)

/** Read a directory's *.si files into a { filename: contents } map (sorted). */
function readSiDir(rel: string): Record<string, string> {
    const dir = join(SRC, rel)
    const out: Record<string, string> = {}
    for (const f of readdirSync(dir).filter(f => f.endsWith('.si')).sort()) {
        out[f] = readFileSync(join(dir, f), 'utf-8')
    }
    return out
}

/** Read the stdlib into a { relpath: contents } map: top-level `*.si` plus the
 *  `gc/` shadow subdir (keyed `gc/<name>.si`).  Drives bare-name `@use 'io';`
 *  resolution from the inlined copy in the browser / compiled-binary builds. */
function readStdlib(): Record<string, string> {
    const out: Record<string, string> = readSiDir('stdlib')
    const gcDir = join(SRC, 'stdlib', 'gc')
    for (const f of readdirSync(gcDir).filter(f => f.endsWith('.si')).sort()) {
        out[`gc/${f}`] = readFileSync(join(gcDir, f), 'utf-8')
    }
    return out
}

const stdWat = read('codegen/std.wat')
const strata = readSiDir('strata')
const builtinModules = readSiDir('strata/modules')
const stdlib = readStdlib()

// Web platform: metadata + every .si file in the directory.
const platformWebMeta = JSON.parse(read('platforms/web/platform.json'))
const platformWebFiles = readSiDir('platforms/web')

const recordLit = (rec: Record<string, string>) =>
    '{\n' + Object.entries(rec).map(([k, v]) => `    ${lit(k)}: ${lit(v)},`).join('\n') + '\n}'

const out = `// SPDX-License-Identifier: MIT
// @generated by compiler/scripts/gen-web-assets.ts — DO NOT EDIT BY HAND.
// Inlined compiler assets for the filesystem-free (browser) build.
// Regenerate with: bun run compiler/scripts/gen-web-assets.ts

export const STD_WAT: string = ${lit(stdWat)}

export const STRATA: Record<string, string> = ${recordLit(strata)}

export const BUILTIN_MODULES: Record<string, string> = ${recordLit(builtinModules)}

export const STDLIB: Record<string, string> = ${recordLit(stdlib)}

export const PLATFORM_WEB: { meta: unknown; files: Record<string, string> } = {
    meta: ${JSON.stringify(platformWebMeta)},
    files: ${recordLit(platformWebFiles)},
}
`

const dest = join(SRC, 'assets.generated.ts')
writeFileSync(dest, out)
console.log(`Wrote ${dest} (${(out.length / 1024).toFixed(1)} KiB) — ` +
    `${Object.keys(strata).length} strata, ${Object.keys(builtinModules).length} modules, ` +
    `${Object.keys(stdlib).length} stdlib, ` +
    `${Object.keys(platformWebFiles).length} web platform files`)
