#!/usr/bin/env bash
# scripts/regen-embedded-bundle.sh — rebuild boot/embedded_bundle.si
# from the strata source tree, in pure shell + awk.  Replaces the TS-
# only generator that used to live inside scripts/build-stage1.ts so
# editing a built-in stratum no longer requires bun.
#
# The output is byte-equal to what scripts/build-stage1.ts produces:
#
#   1. Source dir (default boot/strata/builtin) is read in sorted
#      alphabetical order.
#   2. Each .si file is CRLF-normalized to LF (matches TS's
#      src.replace(/\r\n/g, '\n')).
#   3. Each file's content is escaped for inclusion in a Silicon
#      single-quoted string literal — \, ', \n, \r, \t, \0 get the
#      conventional escapes; everything else passes through as a raw
#      byte (Silicon source is UTF-8).
#   4. An extra '\n' separator is appended after each file (matches
#      TS's bundle += src + '\n' loop).
#   5. The escaped concatenation is wrapped in a Silicon @let
#      definition and written to the output path.
#
# Usage:
#   ./scripts/regen-embedded-bundle.sh                       # defaults
#   ./scripts/regen-embedded-bundle.sh boot/strata/builtin   # custom src
#   ./scripts/regen-embedded-bundle.sh src out.si            # both args

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

SRC_DIR="${1:-boot/strata/builtin}"
OUT="${2:-boot/embedded_bundle.si}"

[ -d "$SRC_DIR" ] || {
  echo "regen-embedded-bundle.sh: source dir '$SRC_DIR' not found" >&2
  exit 1
}

# escape_for_silicon — read a single file from stdin, emit it as the
# escaped byte sequence appropriate for embedding inside a Silicon
# single-quoted string literal.  Order matters: backslash MUST be
# escaped first; subsequent rules add their own backslashes that
# would otherwise be re-doubled.  awk gsub regex/replacement use the
# extra-backslash discipline awk requires.
#
# We slurp the file via RS="\0" so the awk program sees the whole
# content as $0 — gsub then operates byte-by-byte regardless of
# embedded newlines.
escape_for_silicon() {
  awk 'BEGIN { RS = "\0" }
       {
         gsub(/\r/,  "")
         gsub(/\\/,  "\\\\")
         gsub(/'\''/, "\\'\''")
         gsub(/\t/,  "\\t")
         gsub(/\n/,  "\\n")
         gsub(/\0/,  "\\0")
         printf "%s", $0
       }'
}

# Capture the @-prefixed Silicon definition header.  Stable so byte-
# diff of two regenerated bundles is meaningful when only strata
# bodies change.
emit_header() {
  cat <<'EOF'
# AUTO-GENERATED by scripts/build-stage1.ts — do not edit.
# Concatenated source of every src/strata/*.si file, embedded
# as a Silicon string literal so stage1.wasm has its built-in
# strata available without the caller prepending them on stdin.
EOF
}

# Build the bundle into a temp file first so a regen failure mid-
# stream doesn't leave a corrupted output that subsequent builds
# would happily consume.
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  emit_header
  printf "@let EMBEDDED_BUNDLE:String := '"
  # Sorted iteration — matches `Array.prototype.sort()` on filenames.
  for f in $(printf '%s\n' "$SRC_DIR"/*.si | LC_ALL=C sort); do
    [ -f "$f" ] || continue
    escape_for_silicon < "$f"
    printf '\\n'             # the +'\n' the TS loop appends
  done
  printf "';\n"
} > "$TMP"

mv "$TMP" "$OUT"
trap - EXIT
echo "regen-embedded-bundle.sh: ✓ wrote $OUT ($(wc -c < "$OUT") bytes)"
