# scripts/regen-embedded-bundle.ps1 — rebuild boot/embedded_bundle.si
# from the strata source tree (Windows / PowerShell version of the
# shell regenerator).
#
# Output is byte-equal to scripts/regen-embedded-bundle.sh — same
# byte-level escape, same sorted file order, same '\n' file separator.
#
# Usage:
#   .\scripts\regen-embedded-bundle.ps1
#   .\scripts\regen-embedded-bundle.ps1 boot\strata\builtin
#   .\scripts\regen-embedded-bundle.ps1 src out.si

[CmdletBinding()]
param(
  [string]$SrcDir = (Join-Path $PSScriptRoot '..\boot\strata\builtin'),
  [string]$OutPath = (Join-Path $PSScriptRoot '..\boot\embedded_bundle.si')
)

$ErrorActionPreference = 'Stop'

$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
Set-Location $ProjectRoot

if (-not (Test-Path $SrcDir)) {
  Write-Error "regen-embedded-bundle.ps1: source dir '$SrcDir' not found"
  exit 1
}

# Header bytes — must match the shell regenerator verbatim so both
# pipelines produce byte-equal output.  Build with LF endings
# explicitly; PowerShell's default would be CRLF on Windows.
$Header = [System.Text.Encoding]::UTF8.GetBytes(@"
# AUTO-GENERATED by scripts/regen-embedded-bundle.{sh,ps1} — do not edit.
# Concatenated source of every boot/strata/builtin/*.si file, embedded
# as a Silicon string literal so stage1.wasm has its built-in
# strata available without the caller prepending them on stdin.
@let EMBEDDED_BUNDLE:String := '
"@.Replace("`r`n","`n"))
# Trim trailing LF from the header — the next byte is the opening quote
# already included above.
if ($Header[-1] -eq 0x0a) { $Header = $Header[0..($Header.Length - 2)] }

$Footer = [byte[]](0x27, 0x3b, 0x0a)  # ';\n

# escape_bytes — apply the same per-byte escapes used by the shell
# and TS pipelines.  Backslash MUST come first; subsequent rules add
# backslashes that the all-backslash rule would otherwise double.
function ConvertTo-SiliconEscaped {
  param([byte[]]$Bytes)
  # Worst case: every byte becomes two output bytes.
  $out = New-Object byte[] ($Bytes.Length * 2)
  $o = 0
  foreach ($b in $Bytes) {
    switch ($b) {
      0x5c { $out[$o] = 0x5c; $out[$o+1] = 0x5c; $o += 2 }       # \
      0x27 { $out[$o] = 0x5c; $out[$o+1] = 0x27; $o += 2 }       # '
      0x0a { $out[$o] = 0x5c; $out[$o+1] = 0x6e; $o += 2 }       # \n
      0x0d {                                                     } # strip \r (CRLF→LF normalization)
      0x09 { $out[$o] = 0x5c; $out[$o+1] = 0x74; $o += 2 }       # \t
      0x00 { $out[$o] = 0x5c; $out[$o+1] = 0x30; $o += 2 }       # \0
      default { $out[$o] = $b; $o += 1 }
    }
  }
  return $out[0..($o - 1)]
}

# Build the bundle into memory first; write atomically at the end so
# a regen failure mid-stream doesn't corrupt the existing output.
$stream = New-Object System.IO.MemoryStream
$stream.Write($Header, 0, $Header.Length)

$siFiles = Get-ChildItem -Path $SrcDir -Filter '*.si' -File | Sort-Object Name
foreach ($f in $siFiles) {
  $raw = [System.IO.File]::ReadAllBytes($f.FullName)
  $escaped = ConvertTo-SiliconEscaped -Bytes $raw
  $stream.Write($escaped, 0, $escaped.Length)
  # The +'\n' the TS loop appends after each file.
  $sep = [byte[]](0x5c, 0x6e)  # literal \n
  $stream.Write($sep, 0, $sep.Length)
}

$stream.Write($Footer, 0, $Footer.Length)
[System.IO.File]::WriteAllBytes($OutPath, $stream.ToArray())
$stream.Dispose()

Write-Host "regen-embedded-bundle.ps1: ✓ wrote $OutPath ($((Get-Item $OutPath).Length) bytes)"
