// SPDX-License-Identifier: MIT
/**
 * ADR 0017 — the spec-generated Node/Bun modules ship and run end-to-end.
 *
 * `path.si` (from @types/node) and `bun.si` (from bun-types) are generated by the
 * adapters, written into compiler/src/strata/modules/, and bundled as built-in
 * modules — so a Silicon program calls them as `path::basename(…)` /
 * `bun::nanoseconds()`.  This compiles such a program and runs the WASM against a
 * host that marshals linear `String` params/results (readLenString/allocLenString
 * over the guest's exported `alloc`), exactly as the generated js-host shims do.
 */

import { test, expect, describe } from 'bun:test'
import { compile } from '../src/caas/index'
import { loadModules } from '../src/modules/loader'

const mods = loadModules(process.cwd())

function compileBin(src: string): Uint8Array {
    const r: any = compile(src, { file: 'm.si', moduleRegistry: mods, target: 'host', platform: 'bun', emitBinary: true } as any)
    expect(r.diagnostics ?? []).toEqual([])
    return r.binary
}

/** Build the marshalling host (mirrors cli/src/host/js-host.ts buildImports). */
function makeHost() {
    const state: { memory?: WebAssembly.Memory; alloc?: (n: number) => number } = {}
    const readLenString = (ptr: number): string => {
        const v = new DataView(state.memory!.buffer)
        const len = v.getInt32(ptr, true)
        return new TextDecoder().decode(new Uint8Array(state.memory!.buffer, ptr + 4, len))
    }
    const allocLenString = (s: string): number => {
        const bytes = new TextEncoder().encode(s)
        const ptr = state.alloc!(4 + bytes.length)
        const v = new DataView(state.memory!.buffer)
        v.setInt32(ptr, bytes.length, true)
        new Uint8Array(state.memory!.buffer, ptr + 4, bytes.length).set(bytes)
        return ptr
    }
    const imports = {
        env: { print: () => {}, read: () => 0 },
        path: {
            is_absolute: (p: number) => require('node:path').isAbsolute(readLenString(p)),
            basename: (p: number, s: number) => allocLenString(require('node:path').basename(readLenString(p), readLenString(s))),
        },
        bun: { nanoseconds: () => (globalThis as any).Bun.nanoseconds() },
    }
    return { imports, bind: (inst: WebAssembly.Instance) => { state.memory = (inst.exports as any).memory; state.alloc = (inst.exports as any).alloc }, readLenString }
}

describe('bindgen — generated Node/Bun modules run end-to-end', () => {
    test('path::is_absolute (String param → Bool) — generated from @types/node', async () => {
        const bin = compileBin(`\\\\ check_abs () -> Int
@fn check_abs := { @if(path::is_absolute('/usr/bin'), { 1 }, { 0 }) };
\\\\ check_rel () -> Int
@fn check_rel := { @if(path::is_absolute('relative/path'), { 1 }, { 0 }) };
@export check_abs;
@export check_rel;`)
        const host = makeHost()
        const inst = new WebAssembly.Instance(await WebAssembly.compile(bin), host.imports)
        host.bind(inst)
        expect((inst.exports as any).check_abs()).toBe(1)   // "/usr/bin" is absolute
        expect((inst.exports as any).check_rel()).toBe(0)   // "relative/path" is not
    })

    test('path::basename (String param → String result) — full marshalling', async () => {
        const bin = compileBin(`\\\\ base () -> String
@fn base := { path::basename('/a/b/c.txt', '') };
@export base;`)
        const host = makeHost()
        const inst = new WebAssembly.Instance(await WebAssembly.compile(bin), host.imports)
        host.bind(inst)
        const ptr = (inst.exports as any).base()             // host allocates "c.txt" in guest memory
        expect(host.readLenString(ptr)).toBe('c.txt')
    })

    test('bun::nanoseconds (Float, no strings) — generated from bun-types', async () => {
        const bin = compileBin(`\\\\ now () -> Float
@fn now := { bun::nanoseconds() };
@export now;`)
        const host = makeHost()
        const inst = new WebAssembly.Instance(await WebAssembly.compile(bin), host.imports)
        host.bind(inst)
        expect((inst.exports as any).now()).toBeGreaterThan(0)
    })

    test('bun::strip_ansi (Tier-1 JSString) — crosses as externref, ZERO linear marshalling', async () => {
        // bun.si is generated Tier-1: strings are JSString (externref).  The
        // binding lowers to an externref import + result, and the host shim
        // passes JS strings directly — no readLenString/allocLenString.
        const bin = compileBin(`\\\\ run (JSString) -> JSString
@fn run s := { bun::strip_ansi(s) };
@export run;`)
        // The param/result are externref, not an i32 pointer.
        const inst = new WebAssembly.Instance(await WebAssembly.compile(bin), {
            env: { print: () => {}, read: () => 0 },
            bun: { strip_ansi: (s: string) => (globalThis as any).Bun.stripANSI(s) },
        })
        // A real JS string (ANSI-coded) crosses in and out as an externref.
        expect((inst.exports as any).run('\x1b[31mhello\x1b[0m world')).toBe('hello world')
    })
})
