// SPDX-License-Identifier: MIT
/**
 * ADR 0017/0018 — the generated CONSTRUCTED Web interface modules run end-to-end.
 *
 * `url.si` / `url_search_params.si` / `headers.si` / `text_encoder.si` /
 * `text_decoder.si` are generated by the `webiface` adapter from the real
 * @webref/idl corpus and shipped as built-in modules.  A Silicon program
 * `new`s an object (`url::create(…)` → a JSValue handle) and operates on it
 * through instance methods / getters / setters whose first arg is that handle —
 * every value crossing as an externref (Tier-2), nothing marshalled, the engine
 * GC-ing the objects.  This compiles such programs and runs them under Bun with
 * a host that mirrors the generated shims (Bun has URL/Headers/TextEncoder/… as
 * globals).
 *
 * Together these cover all six binding shapes — construct, instance method,
 * getter, setter, static method, and (the headline) CROSS-HANDLE threading: a
 * handle produced by one interface consumed by another.
 */

import { test, expect, describe } from 'bun:test'
import { compile } from '../src/caas/index'
import { loadModules } from '../src/modules/loader'

const mods = loadModules(process.cwd())   // url.si / headers.si / … are real built-ins on disk

function compileBin(src: string): Uint8Array {
    const r: any = compile(src, { file: 'm.si', moduleRegistry: mods, target: 'host', platform: 'bun', emitBinary: true } as any)
    expect(r.diagnostics ?? []).toEqual([])
    return r.binary
}

/** Host shims for the chosen Web interfaces — these mirror the generated
 *  js-host.ts blocks (construct → `new Iface()`, method → `self.m(args)`,
 *  getter → `self.attr`, setter → `self.attr = v`, static → `Iface.m(args)`). */
const HOST = {
    env: { print: () => {}, read: () => 0 },
    url: {
        create: (u: any) => new URL(u),                    // optional `base` dropped (1-arg WHATWG form)
        search_params: (self: any) => self.searchParams,
        pathname: (self: any) => self.pathname,
        set_pathname: (self: any, v: any) => { self.pathname = v },
        href: (self: any) => self.href,
        can_parse: (u: any) => URL.canParse(u),
    },
    url_search_params: {
        create: (init: any) => new URLSearchParams(init),
        get: (self: any, name: any) => self.get(name),     // may return null → nullable externref
        set: (self: any, name: any, value: any) => { self.set(name, value) },
        to_string: (self: any) => self.toString(),
    },
    headers: {
        create: () => new Headers(),
        set: (self: any, n: any, v: any) => { self.set(n, v) },
        append: (self: any, n: any, v: any) => { self.append(n, v) },
        get: (self: any, n: any) => self.get(n),
    },
    text_encoder: {
        create: () => new TextEncoder(),
        encode: (self: any, input: any) => self.encode(input),
    },
    text_decoder: {
        create: (label: any) => new TextDecoder(label),
        decode: (self: any, input: any) => self.decode(input),
    },
}

async function run(src: string): Promise<any> {
    const bin = compileBin(src)
    return new WebAssembly.Instance(await WebAssembly.compile(bin), HOST as any).exports as any
}

describe('bindgen — constructed Web interface modules run end-to-end (Tier-2)', () => {
    test('CROSS-HANDLE: URL → searchParams handle → URLSearchParams.get (construct + getter-handle + method)', async () => {
        // `url::create` constructs a URL handle; `url::search_params` getter returns
        // a URLSearchParams handle; `url_search_params::get` consumes THAT handle —
        // a handle produced by one interface threaded into another, all externref.
        const ex = await run(`\\\\ getq (JSString, JSString) -> JSString
@fn getq u, key := { url_search_params::get(url::search_params(url::create(u)), key) };
@export getq;`)
        expect(ex.getq('https://a.b/p?x=1&y=2&y=3', 'y')).toBe('2')   // first 'y'
        expect(ex.getq('https://a.b/p?x=1&y=2', 'x')).toBe('1')
    })

    test('CROSS-HANDLE: TextEncoder.encode → Uint8Array handle → TextDecoder.decode (multibyte round-trip)', async () => {
        // encode returns a Uint8Array as a JSValue handle; decode takes it back.
        // The bytes never touch linear memory — the typed array crosses as externref.
        const ex = await run(`\\\\ roundtrip (JSString, JSString) -> JSString
@fn roundtrip label, s := { text_decoder::decode(text_decoder::create(label), text_encoder::encode(text_encoder::create(), s)) };
@export roundtrip;`)
        expect(ex.roundtrip('utf-8', 'héllo wörld')).toBe('héllo wörld')   // multibyte UTF-8 survives
        expect(ex.roundtrip('utf-8', '日本語 🦀')).toBe('日本語 🦀')
    })

    test('getter + static method: url::pathname (getter) and url::can_parse (static → Bool)', async () => {
        // The optional `base` is DROPPED (Silicon has no optional params and "" ≠
        // omitted), so the 1-arg WHATWG form is exposed and answers correctly.
        const ex = await run(`\\\\ path (JSString) -> JSString
@fn path u := { url::pathname(url::create(u)) };
\\\\ valid (JSString) -> Bool
@fn valid u := { url::can_parse(u) };
@export path;
@export valid;`)
        expect(ex.path('https://a.b/p/q?x=1')).toBe('/p/q')
        expect(ex.valid('https://x.y')).toBe(1)     // static URL.canParse → true
        expect(ex.valid('not a url')).toBe(0)       // → false (correct; no forced base)
    })

    test('nullable result: url_search_params::get of a missing key returns null, no trap', async () => {
        // get → USVString? — a missing key yields null.  The extern result is a
        // NULLABLE externref, so this returns cleanly instead of trapping.
        const ex = await run(`\\\\ getq (JSString, JSString) -> JSString
@fn getq u, key := { url_search_params::get(url::search_params(url::create(u)), key) };
@export getq;`)
        expect(ex.getq('https://a.b/p?x=1', 'absent')).toBeNull()   // missing key → null, not a trap
    })

    test('setter: url::set_pathname mutates the handle in place; read back via href', async () => {
        // The setter returns Void and mutates the SAME externref object; the @local
        // holds the handle across the mutate-then-read sequence.
        const ex = await run(`\\\\ set_path (JSString, JSString) -> JSString
@fn set_path u, p := {
    \\\\ h JSValue
    @mut h := url::create(u);
    url::set_pathname(h, p);
    url::href(h)
};
@export set_path;`)
        expect(ex.set_path('https://a.b/old', '/new')).toBe('https://a.b/new')
    })

    test('construction + instance methods: Headers create / set / append / get (handle threaded through a chain)', async () => {
        // create() with no args, then set + append accumulate on the handle.
        const ex = await run(`\\\\ build (JSString, JSString, JSString) -> JSString
@fn build k, v1, v2 := {
    \\\\ h JSValue
    @mut h := headers::create();
    headers::set(h, k, v1);
    headers::append(h, k, v2);
    headers::get(h, k)
};
@export build;`)
        expect(ex.build('X-Tag', '1', '2')).toBe('1, 2')   // Headers join appended values
    })

    test('construct-from-string + setter + toString: URLSearchParams', async () => {
        const ex = await run(`\\\\ run (JSString, JSString, JSString) -> JSString
@fn run init, k, v := {
    \\\\ p JSValue
    @mut p := url_search_params::create(init);
    url_search_params::set(p, k, v);
    url_search_params::to_string(p)
};
@export run;`)
        expect(ex.run('a=1&b=2', 'a', '9')).toBe('a=9&b=2')
    })
})
